apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-app
  namespace: test
spec:
  replicas: 5
  selector:
    matchLabels:
      app: nodejs-app
  template:
    metadata:
      labels:
        app: nodejs-app
    spec:
      containers:
      - name: nodejs-app
        image: your-docker-username/nodejs-app:latest
        ports:
        - containerPort: 3000
