name: ci-cd

on:
  push:
    branches:
      - 'main'

jobs:
  docker-build-push-and-kubectl-apply:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Read Version from package.json
        run: echo "PACKAGE_VERSION=$(jq -r .version ./nodejsApp/package.json)" >> $GITHUB_ENV
        shell: bash
        working-directory: ./
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        run: docker build -t serhatd/nodejsapp:${{ env.PACKAGE_VERSION }} ./nodejsApp && docker push serhatd/nodejsapp:${{ env.PACKAGE_VERSION }}
      -
        name: Deploy to Kubernetes
        run: |
          echo "$KUBE_CONFIG_DATA" > kubeconfig.yaml
          kubectl apply -f ./nodejsApp/deployment.yaml --kubeconfig=kubeconfig.yaml
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}